name: publish
version: 2.2.0
synopsis: Publishing tools for papers, books, and presentations
description: |
  Tools for rendering markdown-centric documents into PDFs.
  
  A description of this package, a list of features, and some background
  to its design is contained in the
  <https://github.com/oprdyn/publish/blob/master/README.markdown README>
  on GitHub.
  
  The main program, @render@, is available via a Docker image at
  <https://hub.docker.com/r/oprdyn/publish-render docker.io/oprdyn/publish-render:latest>

stability: experimental
license: MIT
license-file: LICENSE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2016-2020 Operational Dynamics and Others
category: Text
tested-with: GHC == 8.6
github: oprdyn/publish

dependencies:
 - base >= 4.11 && < 5
 - bytestring
 - chronologique
 - deepseq
 - directory
 - filepath
 - hinotify
 - megaparsec
 - pandoc-types
 - pandoc
 - template-haskell
 - text
 - typed-process
 - core-text >= 0.2.2.3
 - core-program >= 0.2.2.3
 - unix
 - unordered-containers

ghc-options: -threaded -Wall -Wwarn -fwarn-tabs

executables:
  render:
    source-dirs: src
    main: RenderMain.hs
    other-modules:
     - Environment
     - LatexPreamble
     - LatexOutputReader
     - PandocToMarkdown
     - ParseBookfile
     - RenderDocument
     - Utilities

  format:
    source-dirs: src
    main: FormatMain.hs
    other-modules:
     - FormatDocument
     - PandocToMarkdown

  static:
    source-dirs: src
    main: StaticMain.hs
    other-modules:
     - Environment
     - ParseBookfile
     - StaticDocument
     - Utilities

tests:
  check:
    dependencies:
     - hspec
    ghc-options: -threaded
    source-dirs:
     - src
     - tests
    main: TestSuite.hs
    other-modules:
     - CheckBookfileParser
     - CheckTableProperties
     - CompareFragments
     - Environment
     - FormatDocument
     - PandocToMarkdown
     - ParseBookfile
 

