name: publish
version: 2.2.2
synopsis: Publishing tools for papers, books, and presentations
description: |
  Tools for rendering markdown-centric documents into PDFs. There are two
  programs:
  
    [/render/]for generating PDFs from Markdown and LaTeX input; and

    [/format/]for word-wrapping and nicely formatting Markdown files.
  
  A description of this package, a list of features, and some background
  to its design is contained in the
  <https://github.com/aesiniath/publish/blob/main/README.md README>
  on GitHub.

stability: experimental
license: MIT
license-file: LICENSE
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2016-2021 Athae Eredh Siniath and Others
category: Text
tested-with: GHC == 8.10.4
github: aesiniath/publish

dependencies:
 - base >= 4.11 && < 5
 - bytestring
 - chronologique
 - deepseq
 - directory
 - filepath
 - megaparsec
 - pandoc-types >= 1.22
 - pandoc >= 2.11
 - template-haskell
 - text
 - typed-process
 - core-text >= 0.3.0
 - core-data
 - core-program >= 0.2.7
 - unix
 - unordered-containers

ghc-options: -threaded -Wall -Wwarn -fwarn-tabs

executables:
  render:
    source-dirs: src
    main: RenderMain.hs
    other-modules:
     - Environment
     - LatexPreamble
     - LatexOutputReader
     - PandocToMarkdown
     - ParseBookfile
     - RenderDocument
     - Utilities

  format:
    source-dirs: src
    main: FormatMain.hs
    other-modules:
     - FormatDocument
     - PandocToMarkdown

tests:
  check:
    dependencies:
     - hspec
    ghc-options: -threaded
    source-dirs:
     - src
     - tests
    main: TestSuite.hs
    other-modules:
     - CheckBookfileParser
     - CheckTableProperties
     - CompareFragments
     - Environment
     - FormatDocument
     - PandocToMarkdown
     - ParseBookfile
 

