resolver: lts-18.12

packages:
  - .

extra-deps:
- git: https://github.com/aesiniath/unbeliever.git
  commit: dd12832784502584b4a255e312c2b60efba0ab88
  subdirs:
  - core-text
  - core-data
  - core-program

