resolver: lts-17.14

packages:
  - .

extra-deps:
  - core-program-0.2.7.1
  - hslua-module-path-0.1.0.1
  - texmath-0.12.3
  - jira-wiki-markup-1.4.0
  - pandoc-2.14
  - citeproc-0.4
  - commonmark-0.2
  - commonmark-extensions-0.2.1.2
  - commonmark-pandoc-0.2.1
  - haddock-library-1.10.0
  - unicode-collation-0.1.3

nix:
  packages: [zlib]


